characters_db = [
    {
        "id": 1,
        "name": "Grim Flesh",
        "class": "Fanged Deserter",
        "hp": 8,
        "max_hp": 8,
        "strength": 14,
        "agility": 9,
        "presence": 7,
        "toughness": 12,
        "omens": 2,
        "silver": 12,
        "weapon": "Rusty cleaver (d6)",
        "armor": "Patched leather (1)",
        "abilities": ["Bloodlust", "Smell of rot"],
        "misfortune": "Hunted by former legion",
        "is_dead": False,
        "created_at": "2024-01-15"
    },
    {
        "id": 2,
        "name": "Silent Wraith",
        "class": "Gutterborn Scum",
        "hp": 4,
        "max_hp": 6,
        "strength": 8,
        "agility": 15,
        "presence": 10,
        "toughness": 11,
        "omens": 1,
        "silver": 3,
        "weapon": "Sharpened spoon (d4)",
        "armor": "Rags (0)",
        "abilities": ["Filth magic", "Scurry"],
        "misfortune": "Plague-ridden, coughs blood",
        "is_dead": False,
        "created_at": "2024-01-15"
    },
    {
        "id": 3,
        "name": "Bone Prophet",
        "class": "Esoteric Hermit",
        "hp": 6,
        "max_hp": 6,
        "strength": 7,
        "agility": 8,
        "presence": 16,
        "toughness": 9,
        "omens": 3,
        "silver": 0,
        "weapon": "Cursed staff (d6, cursed)",
        "armor": "Threadbare robe (0)",
        "abilities": ["Dark prophecy", "Whisper of bones"],
        "misfortune": "Blind, sees only death",
        "is_dead": True,
        "death_cause": "Self-fulfilling prophecy",
        "created_at": "2024-01-10"
    },
    {
        "id": 4,
        "name": "Iron Maw",
        "class": "Wretched Royalty",
        "hp": 10,
        "max_hp": 14,
        "strength": 13,
        "agility": 11,
        "presence": 6,
        "toughness": 15,
        "omens": 0,
        "silver": 47,
        "weapon": "Ceremonial dagger (d6, silver)",
        "armor": "Tarnished chainmail (2)",
        "abilities": ["Noble bearing", "Tax collection"],
        "misfortune": "Last of fallen dynasty",
        "is_dead": False,
        "created_at": "2024-01-14"
    },
    {
        "id": 5,
        "name": "Ashen Tongue",
        "class": "Occult Herbmaster",
        "hp": 5,
        "max_hp": 7,
        "strength": 9,
        "agility": 12,
        "presence": 14,
        "toughness": 10,
        "omens": 2,
        "silver": 8,
        "weapon": "Poisoned darts (d4, poison)",
        "armor": "Ash-coated cloak (1)",
        "abilities": ["Poultice crafting", "Speak with rot"],
        "misfortune": "Tongue burned to ash",
        "is_dead": False,
        "created_at": "2024-01-15"
    }
]
